<?xml version="1.0"?>
<robot name="pole_without_cables" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--
    To generate pole.urdf
      rosrun xacro xacro - -inorder pole.urdf.xacro > pole.urdf

    To generate the pole.sdf
      gz sdf -p  ./pole.urdf> ./pole.sdf
    
    then, create the model in the ~/.gazebo/models folder
  -->

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:property name="pole_height" value="10" />
  <xacro:property name="pole_mass" value="100" />
  <xacro:property name="pole_radius" value="0.25" />

  <xacro:property name="top_length" value="4.2" />
  <xacro:property name="top_height" value="0.4" />
  <xacro:property name="top_width" value="0.4" />


  <!-- materials for visualization -->
  <xacro:include filename="$(find plt_description)/urdf/materials.urdf.xacro" />

  <!-- cables macros -->
  <xacro:include filename="$(find plt_description)/urdf/cable.urdf.xacro" />

  <gazebo>
    <static>true</static>
  </gazebo>

  <link name="footprint"/>
  <!-- Link Falso -->

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="base_link"/>
  </joint>

  <!-- pole -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${pole_height}" radius="${pole_radius}"/>
      </geometry>
      <material name="Brown"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${pole_height}" radius="${pole_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${pole_mass}"/>
      <inertia ixx="${0.25*pole_mass*pole_radius*pole_radius + 0.083333*pole_mass*pole_height*pole_height}" ixy="0.0" ixz="0.0" iyy="${0.25*pole_mass*pole_radius*pole_radius + 0.083333*pole_mass*pole_height*pole_height}" iyz="0.0" izz="${0.5*pole_mass*pole_radius*pole_radius}" />
    </inertial>
  </link>

  <!-- Trocando a cor -->
	<gazebo reference="base_link">
		<material>Gazebo/Orange</material>
	</gazebo>

  <!-- Apoio dos Cabos-->
  <joint name="pole_to_top" type="fixed">
    <parent link="base_link"/>
    <child link="top"/>
    <origin xyz="0 0 ${pole_height/2}" rpy="0 0 0" />
  </joint>

  <link name="top">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
      <geometry>
        <box size="${top_length} ${top_height} ${top_width}"/>
      </geometry>
      <material name="Brown"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
      <geometry>
        <box size="${top_length} ${top_height} ${top_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- Trocando a cor -->
	<gazebo reference="top">
		<material>Gazebo/Orange</material>
	</gazebo>

  <!-- Cables -->
  <!--
  <xacro:cable_macro prefix="center" parent="top" reflect="0" parent_length="${top_length}"/>
  <xacro:cable_macro prefix="left" parent="top" reflect="1" parent_length="${top_length}"/>
  <xacro:cable_macro prefix="right" parent="top" reflect="-1" parent_length="${top_length}"/>
  -->

</robot>